name: credit-risk-ml
channels:
  - defaults
dependencies:
  - black
  - ipykernel
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pre-commit
  - pytest
  - python=3.12
  - ruff
  - scikit-learn
  - shap
  - hydra-core
  - omegaconf
  - pyarrow
  - nbstripout
prefix: /Users/ThadCreech/opt/anaconda3/envs/credit-risk-ml
